version: '2'

services:
  artifactory:
    build:
      context: artifactory
      dockerfile: ./Dockerfile
    image: artifactory-swampup
    container_name: artifactory-server
    ports:
      - "8081:8081"
#    volumes:
#      - "${HOST_ARTIFACTORY_HOME}/logs:/var/opt/jfrog/artifactory/logs"
  gitlab:
    build:
      context: gitlab
      dockerfile: ./Dockerfile
    image: gitlab-swampup
    container_name: gitlab-server
    ports:
      - "8082:80"
  jenkins:
    build:
      context: jenkins
      dockerfile: ./Dockerfile
    image: jenkins-swampup
    container_name: jenkins-server
    ports:
      - "8080:8080"

networks:
  default:
    external:
      name: swampup
